import argparse

# the log file contains timestamps and a task numbers that is scheduled in
#     3 SC 32000000
#  13169 TC 1 defaultTask
#  30172 TC 2 myTaskA
#  45611 TC 3 myTaskB
#  61050 TC 4 myTaskC
#  75394 TC 5 IDLE
#  92393 TC 6 Tmr Svc
# 102355 TI 4
# 546249 TO 4
# 552488 TI 3
# 1819138 TO 3
# 1830209 TI 2
# 2459150 TO 2

parser = argparse.ArgumentParser(description='plot a timeline diagram for a logfile generated by FreeRTOS running on an STM32 MCU')
parser.add_argument('logfile', type=str, help='the logfile to be plotted')

try:
    args = parser.parse_args()
except Exception as e:
    exit(1)

with open(args.logfile) as f:
    lines = f.readlines()

SystemCoreClock = 32_000_000 # default
task_names = {}
events = []
for line in lines:
    tokens = line.split()
    if(not tokens):
        continue    # skip blank lines
    timestamp = int(tokens[0])*1e3/SystemCoreClock # MCU clock --> ms
    action = tokens[1]
    task =  int(tokens[2])

    if action == 'TI':
        t_start = timestamp
    elif action == 'TO':
        t_stop = timestamp
        if t_start is None:
            print('TI missing before TO at '+timestamp)
            quit()
        events.append(
            {
                'task': task,
                't_start': t_start,
                't_stop': t_stop,
            }
        )
        t_start = None
    elif action == 'TC':
        task_names[task] = ' '.join(tokens[3:]) # task name
    elif action == 'CC':
        SystemCoreClock = int(tokens[2])
    else:
        print('unknown action ignored: '+line)

categories = sorted(list(set([e['task'] for e in events])))

import matplotlib.pyplot as plt

plt.figure()
plt.title("TimeDoctor Plot")
plt.xlabel("time [ms]")
plt.ylabel("task scheduled")
plt.minorticks_on()
plt.grid(which='both', axis='x')
plt.yticks(categories, [task_names[key] for key in categories])
for e in events:
    plt.hlines( e['task'], e['t_start'], e['t_stop'], 'C{}'.format(e['task']) )
plt.show()

# the end